### ISSUE TITLE
'Files' has a diamond beside app name in Show Applications view

### ISSUE THREAD

**Issue by kdwk** [Vanilla-OS/testing-issues#17]
![Screenshot from 2022-10-02 08-20-53](https://user-images.githubusercontent.com/39268094/193432830-a2fb6736-04d1-4020-9ac6-5ef4085e9a3b.png)

**Comment by mirkobrombin** [comment]
Removed in 1.2.6

**Comment by kbdharun** [comment]
> Removed in 1.2.6. The user can still browse apx apps in the vanilla control center.

I will update the docs regarding it later today.
