### ISSUE TITLE
Multi monitor setup settings not persisting after reboot.

### ISSUE THREAD

**Issue by eddiecsilva** [Vanilla-OS/testing-issues#23]
I tried adjusting the monitor settings both through Nvidia Controll Setings and through the Gnome Settings, in both cases the adjustments are lost when restarting the computer.

My installation has 3 monitors 2 Dell (1440x90/HDMI and DP) and 1 MSI (2560x1440/DP)
![Captura de tela de 2022-10-27 21-17-39](https://user-images.githubusercontent.com/751446/198420881-daaf4511-34ef-4bee-8545-0d2e9c7e3fc6.png)
![Captura de tela de 2022-10-27 21-17-48](https://user-images.githubusercontent.com/751446/198420885-5d042774-304e-4d08-9708-6a19a6b424ed.png)

**Comment by mirkobrombin** [comment]
Does this persist in latest builds?

**Comment by eddiecsilva** [comment]
I will run further tests and let you know the result.

**Comment by teh404guy** [comment]
The nvidia display config is using the x config file as per this screenshot 

![Screenshot_20221207-144613_Firefox_1](https://user-images.githubusercontent.com/62482190/206198184-ed87cc3f-3f0f-4d0e-a578-9df4fd36108b.png)
