### ISSUE TITLE
Force installation of language packs and dictionaries after installation

### ISSUE THREAD

**Issue by eddiecsilva** [Vanilla-OS/testing-issues#24]
When choosing a language for the system installation (such as Brazilian Portuguese) it is necessary to enter the control panel in the languages tab and manually confirm the installation of extra packages for the language and dictionaries.

This installation could be forced during the "First Setup" automatically, making the experience of using the system in other languages more complete.

![Captura de tela de 2022-10-27 21-23-22](https://user-images.githubusercontent.com/751446/198421344-e214edbc-c4d0-4775-b487-0bb79b1b44af.png)

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/Vanilla-OS/gnome-language-selector
