### ISSUE TITLE
Installer always set system to english regardless of chosen language

### ISSUE THREAD

**Issue by r0xANDt0l** [Vanilla-OS/testing-issues#38]
I set the language on spanish on the installer, but when I rebooted Vanilla, the OS was set to english, I had to go to Language support to add spanish, and then set it on gnome settings. The only thing in spanish was Vanilla Control Center

**Comment by riomccloud** [comment]
> This does not appear in my recent tests. I guess some commits fixed it. Also the language support installer now works from GNOME Control Center, so it is possible to install any other language from there.

I'm using the stable release version and I had the same issue with the Brazilian Portuguese language. Perhaps there is some trigger for this problem to happen only in some cases.
